language: node_js
node_js:
  - 'lts/*'
  - '10'
  - '12'
  - '13'
  - '14'

before_deploy: 'yarn docs'

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: 'docs'
  on:
    branch: master

script:
  - yarn format
  - yarn test:unit
  - yarn test:int

cache: yarn
